### ISSUE TITLE
Unable to load asset: assets/rrect.json

### ISSUE THREAD

**Issue by songshitong** [dnfield/lottie-flutter#17]
i copied  example/LottieDemo  to  my  project    but  there is an error occur

error  log :
```
Unable to load asset: assets/rrect.json
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
<asynchronous suspension>
#2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
#5      loadAsset (package:oldfriendspub/pages/mine/about_us_page.dart:154:8)
<asynchronous suspension>
#6      _LottieDemoState._loadButtonPressed (package:oldfriendspub/pages/mine/about_us_page.dart:56:5)
#7      _LottieDemoState.initState (package:oldfriendspub/pages/mine/about_us_page.dart:47:5)
#8      StatefulElement._firstBuild (packa<…>
```

DemoPage:
![image](https://user-images.githubusercontent.com/26601878/51899118-58782180-23ed-11e9-951f-e0ec274aa780.png)

pubspec.yaml:
![image](https://user-images.githubusercontent.com/26601878/51899249-96754580-23ed-11e9-9a83-a66199e50378.png)

i am a newer in flutter, would you please help me?

**Comment by PramUkesh** [comment]
@songshitong  may be because you are not including assets in pubspec.yaml
ping me if you correctly mention this
just found that assets/rrect.json is not in assets so remove that from array

**Comment by PramUkesh** [comment]
@songshitong  reply me if it is resolved or not

**Comment by PramUkesh** [comment]
@songshitong  
and one thing about posting an issue is use insert code option or quote block your issue referenced all the 1 - 8 issues because 
number followed by hash reference to issue below without code block reference issue 1 for this repo. so post carefully
`#1`

**Comment by dnfield** [comment]
Those are safe to delete.

I need to restructure this project. Sorry about that.

**Comment by songshitong** [comment]
it will be a good  job.

thanks for your help.
