### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by huangturen** [dnfield/lottie-flutter#2]
Dear dnfield：

when I try to test your Lottie-flutter project, some issues happened:

Because every version of flutter_test from sdk depends on test 1.3.0 and lottie_flutter depends on test >=0.12.34 <1.0.0, flutter_test from sdk is forbidden.
So, because lottie_flutter depends on flutter_test any from sdk, version solving failed.
pub get failed (1)

**Comment by dnfield** [comment]
This package needs some updating.  I'm not entirely sure when I'll be able to get to that right now, but it shouldn't be terribly involved.

**Comment by dnfield** [comment]
Fixed in e23a26d
